# Generated by Django 4.1.1 on 2022-09-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_post_parent_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='avatar',
            field=models.ImageField(upload_to='avatars'),
        ),
    ]
