# Generated by Django 4.1.1 on 2022-09-07 17:00

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_post_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='avatar',
            field=models.ImageField(upload_to='avatars', validators=[app.models.Post.validate_image]),
        ),
    ]
