# Generated by Django 4.1.1 on 2022-09-08 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_post_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='parent_comment',
        ),
        migrations.AddField(
            model_name='post',
            name='parent_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app.post'),
        ),
    ]
