# Generated by Django 4.1.1 on 2022-09-25 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_user_delete_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
